name: Convert Markdown to HTML and Deploy

on:
  push:
    paths:
      - 'Backend/Student_Project_Submissions/**.md'

jobs:
  convert_md_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js for actions
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Pandoc
      run: |
        sudo apt-get update && sudo apt-get install -y pandoc

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        pip install beautifulsoup4

    - name: Process Markdown Files
      run: |
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep 'Backend/Student_Project_Submissions/.*\.md$' | xargs)
        if [ -z "$CHANGED_FILES" ]; then
          echo "No Markdown files changed or added in the specified directory."
          exit 0
        fi
        for file in $CHANGED_FILES; do
          echo "Processing $file"
          html_file="${file%.md}.html"
          
          # Convert MD to HTML
          pandoc "$file" -o "$html_file"
          
          # Post-process HTML for divs
          python Backend/MD_to_HTML_Conversion/wrap_in_divs.py "$html_file"
        done

    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Backend/HTML_file_destination/
