name: Convert Markdown to HTML

on:
  push:
    paths:
      - 'Backend/Student_Project_Submissions/**.md'

jobs:
  convert_md:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Set up Node.js for actions
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Pandoc
      run: sudo apt-get update && sudo apt-get install -y pandoc

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: pip install beautifulsoup4

    - name: Process Markdown Files
      run: |
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep 'Backend/Student_Project_Submissions/.*\.md$' | xargs)
        if [ -z "$CHANGED_FILES" ]; then
          echo "No Markdown files changed or added in the specified directory."
          exit 0
        fi
        mkdir -p Backend/HTML_file_destination
        for file in $CHANGED_FILES; do
          echo "Processing $file"
          # Extract just the filename without path for the output
          filename=$(basename "$file")
          html_file="Backend/HTML_file_destination/${filename%.md}.html"
          if pandoc "$file" -o "$html_file"; then
            echo "Converted $file to $html_file"
            if python Backend/MD_to_HTML_Conversion/wrap_in_divs.py "$html_file"; then
              echo "Post-processed $html_file"
            else
              echo "Failed to post-process $html_file"
              exit 1
            fi
          else
            echo "Failed to convert $file to HTML"
            exit 1
          fi
        done

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add Backend/HTML_file_destination/
        git commit -m "Automated: Convert Markdown to HTML"
        git push
